steps:
- id: 'Build image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/laomaojp/github.com/eoslaomao/watchdog:$TAG_NAME', '.']
    
- id: 'Push image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/laomaojp/github.com/eoslaomao/watchdog:$TAG_NAME']

- id:  'make sure kubectl can work'
  name: 'gcr.io/cloud-builders/kubectl'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=laomao'
  - 'KUBECONFIG=/workspace/.kube/config'
  args: ['cluster-info']
     

# Decrypt the file containing the key
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=github_rsa.enc
  - --plaintext-file=/root/.ssh/github_rsa
  - --location=global
  - --keyring=laomaojp
  - --key=github-key
  - --project=laomaojp
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set up git with key and domain
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/github_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/github_rsa
    EOF
    mv known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- id: 'Clone charts'
  name: 'gcr.io/cloud-builders/git'
  args: ['clone','git@github.com:EOSLaoMao/Charts.git']
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- id: 'Init helm' 
  name: 'gcr.io/$PROJECT_ID/helm'
  args: ['init']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=laomao'
  - 'KUBECONFIG=/workspace/.kube/config'

- id: 'Deploy' 
  name: 'gcr.io/$PROJECT_ID/helm'
  args: ['upgrade','-f', '/workspace/Charts/block-producer/charts/watchdog/values.yaml', 'block-producer','/workspace/Charts/block-producer/charts/watchdog']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=laomao'
  - 'KUBECONFIG=/workspace/.kube/config'


